### ISSUE TITLE
Possible clog_free improvement?

### ISSUE THREAD

**Issue by brasko** [mmueller/clog#4]
In our use of clog we have this in clog_free,
     if (_clog_loggers[id]) {
         if (_clog_loggers[id]->opened) {
             close( _clog_loggers[ id ]->fd );
         }
         free( _clog_loggers[ id ] );
+        _clog_loggers[ id ] = 0;

Does this make sense?

**Comment by sunyinkai** [comment]
I think so

**Comment by mmueller** [comment]
Making #7 master ticket for this.
